version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./server/data/postgresql/:/var/lib/postgresql/data

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    depends_on:
      - db
    ports:
      - '8001:8001'